spring:
 application:
  name: auth-service
 config:
    import: optional:configserver:http://localhost:8888
#.....................local values..............
# datasource:
#  url: jdbc:mysql://localhost:3306/expense_auth?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#  username: root
#  password: root
#
# jpa:
#  hibernate: 
#   ddl-auto: update
#  show-sql: true
#  properties: 
#   hibernate: 
#    format_sql: true
#server:
# port: 8081    